""" Methods for the PANAGEA bio-optical in situ dataset.

PANAGEA is the Valente et al. (2022) "version 3" compilation of global
bio-optical in situ data for ocean-colour satellite applications.

PANGAEA: https://doi.org/10.1594/PANGAEA.941318
ESSD paper: https://doi.org/10.5194/essd-14-5737-2022

The compilation ships as seven tab-separated ``.tab`` files, each with a
PANGAEA header block delimited by ``/* ... */`` followed by a single
column-name line and the data. This module loads any of the seven into a
tidy, ``ID``-indexed :class:`pandas.DataFrame` with friendly column names,
and provides helpers to pull individual Rrs / IOP spectra.
"""
import os
import re

import numpy as np
import pandas


# Short logical keys -> .tab filenames for the 7 V3 datasets.
# Users reference datasets by these keys instead of the long filenames.
FILE_CATALOG = {
    'chla': 'insitudb_chla_V3.tab',
    'rrs': 'insitudb_rrs_V3.tab',
    'rrs_sat2': 'insitudb_rrs_satbands2_V3.tab',
    'rrs_sat6': 'insitudb_rrs_satbands6_V3.tab',
    'iop': 'insitudb_iopskdtsm_V3.tab',
    'iop_sat2': 'insitudb_iopskdtsm_satbands2_V3.tab',
    'iop_sat6': 'insitudb_iopskdtsm_satbands6_V3.tab',
}

# Leading PANGAEA column token -> our short variable name.
# These are the spectral / scalar measurement families.
VARIABLE_TOKENS = {
    'RRS': 'rrs',       # remote-sensing reflectance [1/sr]
    'APH': 'aph',       # algal pigment absorption [1/m]
    'acCDOM': 'acdom',  # CDOM + detrital absorption [1/m]
    'bbp': 'bbp',       # particulate backscatter [1/m]
    'KD': 'kd',         # diffuse attenuation [1/m]
    'TSS': 'tss',       # total suspended matter [mg/l] (scalar)
}

# Pre-compiled regexes for parsing column names (see _parse_column).
_RE_UNIT = re.compile(r'\[(.*?)\]')                  # unit inside [ ]
_RE_PAREN = re.compile(r'\((.*)\)')                  # text inside ( )
_RE_NATIVE_WV = re.compile(r'\(at\s+([0-9.]+)\s*nm') # "(at 349.01nm)"
# Sat-band value column, e.g. "(at +-2nm of OLCI-S3A band 11)"
_RE_SATBAND = re.compile(r'of\s+(.+?)\s+band\s+(\S+?)\)')
# Sat-band Lambda column, e.g. "(assigned to OLCI-S3A band 11)" possibly
# prefixed with a variable tag like "aph, assigned to ...".
_RE_LAMBDA = re.compile(r'assigned to\s+(.+?)\s+band\s+(\S+?)\)')


def file_catalog():
    """ Return the catalogue of PANAGEA datasets.

    Generated by JXP and Claude.

    Returns:
        dict: Mapping of short logical key (e.g. ``'rrs'``) to the
            corresponding PANAGEA ``.tab`` filename.
    """
    # Return a copy so callers cannot mutate the module-level dict.
    return dict(FILE_CATALOG)


def panagea_path(path=None):
    """ Resolve the directory holding the PANAGEA V3 data.

    The data are large and are not packaged with ``ocpy``. Resolution order
    is: an explicit ``path`` argument, then ``$OS_COLOR/PANAGEA/V3``.

    Generated by JXP and Claude.

    Args:
        path (str, optional): Explicit path to the ``V3`` directory (the
            directory that contains the ``datasets/`` sub-folder). If None,
            ``$OS_COLOR/PANAGEA/V3`` is used.

    Returns:
        str: Absolute path to the existing ``V3`` directory.

    Raises:
        FileNotFoundError: If no candidate directory exists.
    """
    # Build the candidate list in priority order.
    candidates = []
    if path is not None:
        candidates.append(path)
    os_color = os.getenv('OS_COLOR')
    if os_color is not None:
        candidates.append(os.path.join(os_color, 'PANAGEA', 'V3'))

    # Return the first candidate that exists on disk.
    for cand in candidates:
        if cand is not None and os.path.isdir(cand):
            return os.path.abspath(cand)

    # Nothing found -- report what we looked for.
    raise FileNotFoundError(
        'PANAGEA V3 directory not found. Tried: '
        + (', '.join(str(c) for c in candidates) or '<none>')
        + '. Pass path= or set $OS_COLOR.')


def dataset_file(key, path=None):
    """ Return the full path to one PANAGEA ``.tab`` file.

    Generated by JXP and Claude.

    Args:
        key (str): Logical dataset key from :func:`file_catalog`.
        path (str, optional): Explicit ``V3`` directory (see
            :func:`panagea_path`).

    Returns:
        str: Absolute path to the requested ``.tab`` file.

    Raises:
        KeyError: If ``key`` is not a known dataset key.
    """
    if key not in FILE_CATALOG:
        raise KeyError(
            f"Unknown PANAGEA key '{key}'. "
            f"Valid keys: {sorted(FILE_CATALOG)}")
    # The seven files live in the datasets/ sub-folder of the V3 directory.
    base = panagea_path(path)
    return os.path.join(base, 'datasets', FILE_CATALOG[key])


def find_header_end(filename):
    """ Find the line number ending a PANGAEA ``/* ... */`` header.

    Auto-detection avoids hard-coding a per-file ``skiprows`` value, so the
    loader is robust to any re-download of the dataset.

    Generated by JXP and Claude.

    Args:
        filename (str): Path to a PANGAEA ``.tab`` file.

    Returns:
        int: The 1-based line number of the closing ``*/``. Passing this as
            ``skiprows`` to :func:`pandas.read_csv` leaves the column-name
            line as the header.

    Raises:
        ValueError: If no closing ``*/`` line is found.
    """
    # Scan line by line; the header terminator is a line equal to "*/".
    with open(filename, 'r', encoding='utf-8') as fh:
        for i, line in enumerate(fh, start=1):
            if line.strip() == '*/':
                return i
    raise ValueError(f'No "*/" header terminator found in {filename}')


def _parse_column(col):
    """ Parse one raw PANGAEA column name into metadata.

    Generated by JXP and Claude.

    Args:
        col (str): The raw column name, e.g.
            ``'RRS [1/sr] (at 349.01nm)'``.

    Returns:
        dict: Metadata with keys ``orig`` (original name), ``friendly``
            (clean name), ``role`` (one of ``id``, ``time``, ``lat``,
            ``lon``, ``depth``, ``provenance``, ``qf``, ``spectral``,
            ``spectral_band``, ``lambda``, ``scalar``, ``other``),
            ``variable``, ``unit``, ``long_name``, ``wavelength``,
            ``sensor`` and ``band`` (the latter four may be None).
    """
    meta = {
        'orig': col, 'friendly': None, 'role': 'other', 'variable': None,
        'unit': None, 'long_name': col.split(' [')[0].strip(),
        'wavelength': None, 'sensor': None, 'band': None,
    }
    # Unit (text inside the first [ ]), if present.
    m_unit = _RE_UNIT.search(col)
    if m_unit:
        meta['unit'] = m_unit.group(1)

    # --- Metadata / geocode columns (matched first) -----------------
    if col.startswith('ID'):
        meta.update(role='id', friendly='ID')
        return meta
    if col.startswith('Date/Time'):
        meta.update(role='time', friendly='date_time')
        return meta
    if col.startswith('Latitude'):
        meta.update(role='lat', friendly='lat')
        return meta
    if col.startswith('Longitude'):
        meta.update(role='lon', friendly='lon')
        return meta
    if col.startswith('Depth water'):
        meta.update(role='depth', friendly='depth_m')
        return meta
    if col.startswith('QF time'):
        meta.update(role='qf', friendly='qf_time')
        return meta
    if col.startswith('QF Chl'):
        meta.update(role='qf', friendly='qf_chl')
        return meta

    # --- Provenance comment columns ---------------------------------
    if col.startswith('Comment'):
        # The friendly name is the text inside the parentheses, which the
        # compilers already made descriptive (e.g. "chla_hplc_dataset").
        m = _RE_PAREN.search(col)
        inside = m.group(1).strip() if m else 'comment'
        # Collapse spaces; keep the descriptive token.
        friendly = re.sub(r'\s+', '_', inside.split(' (')[0]).lower()
        meta.update(role='provenance', friendly=friendly)
        return meta

    # --- Chlorophyll a (two methods kept separate) ------------------
    if col.startswith('Chl a'):
        low = col.lower()
        if 'high performance' in low or 'hplc' in low:
            meta.update(role='scalar', variable='chla_hplc',
                        friendly='chla_hplc')
        elif 'fluor' in low or 'spectro' in low:
            meta.update(role='scalar', variable='chla_fluor',
                        friendly='chla_fluor')
        else:
            meta.update(role='scalar', variable='chla', friendly='chla')
        return meta

    # --- Lambda [nm] columns of the sat-band files ------------------
    if col.startswith('Lambda'):
        m = _RE_LAMBDA.search(col)
        if m:
            sensor, band = m.group(1), m.group(2)
            meta.update(role='lambda', sensor=sensor, band=band,
                        friendly=_band_name('lambda', sensor, band))
        else:
            meta.update(role='lambda', friendly='lambda')
        return meta

    # --- Measurement families (RRS, APH, acCDOM, bbp, KD, TSS) ------
    token = col.split(' [')[0].strip()
    variable = VARIABLE_TOKENS.get(token)
    if variable is None:
        return meta  # unrecognised -> role 'other'

    if variable == 'tss':
        # TSS is a single scalar column, not a spectrum.
        meta.update(role='scalar', variable='tss', friendly='tss')
        return meta

    # Sat-band spectral column: wavelength lives in a paired Lambda column.
    m_sat = _RE_SATBAND.search(col)
    if m_sat:
        sensor, band = m_sat.group(1), m_sat.group(2)
        meta.update(role='spectral_band', variable=variable, sensor=sensor,
                    band=band, friendly=_band_name(variable, sensor, band))
        return meta

    # Native-wavelength spectral column: wavelength is in the name.
    m_wv = _RE_NATIVE_WV.search(col)
    if m_wv:
        wv = float(m_wv.group(1))
        meta.update(role='spectral', variable=variable, wavelength=wv,
                    friendly=f'{variable}_{wv:g}')
        return meta

    # Recognised variable but unexpected format -> keep as scalar.
    meta.update(role='scalar', variable=variable, friendly=variable)
    return meta


def _band_name(prefix, sensor, band):
    """ Build a friendly sat-band column name.

    Generated by JXP and Claude.

    Args:
        prefix (str): Variable or role prefix (e.g. ``'rrs'``,
            ``'lambda'``).
        sensor (str): Sensor name (e.g. ``'OLCI-S3A'``).
        band (str): Band identifier (e.g. ``'11'`` or ``'MER1'``).

    Returns:
        str: A compact, spaces-free column name such as
            ``'rrs_OLCI-S3A_band11'``.
    """
    # Replace internal whitespace so the name is a clean token.
    sensor_tok = re.sub(r'\s+', '', sensor)
    return f'{prefix}_{sensor_tok}_band{band}'


def _build_columns(raw_columns):
    """ Build friendly names and metadata for a list of raw columns.

    Generated by JXP and Claude.

    Args:
        raw_columns (list): Raw PANGAEA column names in file order.

    Returns:
        tuple:
            rename (dict): Mapping of raw name -> unique friendly name.
            meta (dict): Mapping of friendly name -> metadata dict (the
                output of :func:`_parse_column`).
    """
    rename, meta, seen = {}, {}, {}
    for col in raw_columns:
        info = _parse_column(col)
        friendly = info['friendly'] or col
        # Guarantee uniqueness by suffixing duplicates.
        if friendly in seen:
            seen[friendly] += 1
            friendly = f'{friendly}__{seen[friendly]}'
            info = dict(info, friendly=friendly)
        else:
            seen[friendly] = 0
        rename[col] = friendly
        meta[friendly] = info
    return rename, meta


def _pair_lambda_columns(meta):
    """ Attach each sat-band value column to its Lambda column.

    Generated by JXP and Claude.

    Args:
        meta (dict): Friendly-name -> metadata mapping. Modified in place to
            add a ``lambda_col`` key on each ``spectral_band`` entry.

    Returns:
        dict: The same ``meta`` mapping, with ``lambda_col`` populated.
    """
    # Index Lambda columns by (sensor, band) so values can find their pair.
    lambdas = {(m['sensor'], m['band']): name
               for name, m in meta.items() if m['role'] == 'lambda'}
    for name, m in meta.items():
        if m['role'] == 'spectral_band':
            m['lambda_col'] = lambdas.get((m['sensor'], m['band']))
    return meta


def load(key, path=None):
    """ Load one PANAGEA dataset into a tidy DataFrame.

    The returned frame is indexed by the global observation ``ID`` and uses
    friendly column names. The full per-column metadata (original name,
    unit, parsed wavelength, sensor / band, ...) is stored in
    ``df.attrs['columns']``; the dataset key and sat-band flag are stored in
    ``df.attrs['kind']`` and ``df.attrs['is_satband']``.

    Generated by JXP and Claude.

    Args:
        key (str): Logical dataset key from :func:`file_catalog`.
        path (str, optional): Explicit ``V3`` directory (see
            :func:`panagea_path`).

    Returns:
        pandas.DataFrame: The dataset, indexed by ``ID``.
    """
    filename = dataset_file(key, path=path)
    # Auto-detect where the PANGAEA header ends, then read the table.
    n_skip = find_header_end(filename)
    # low_memory=False avoids mixed-dtype warnings on the very wide
    # spectral files (pandas otherwise infers types chunk by chunk).
    df = pandas.read_csv(filename, sep='\t', skiprows=n_skip,
                         low_memory=False)

    # Map raw -> friendly names and gather per-column metadata.
    rename, meta = _build_columns(list(df.columns))
    meta = _pair_lambda_columns(meta)
    df = df.rename(columns=rename)

    # Parse Date/Time to real timestamps when present.
    if 'date_time' in df.columns:
        df['date_time'] = pandas.to_datetime(df['date_time'],
                                              errors='coerce')

    # Index by the global observation ID.
    if 'ID' in df.columns:
        df = df.set_index('ID')

    # Stash metadata for downstream helpers.
    df.attrs['columns'] = meta
    df.attrs['kind'] = key
    df.attrs['is_satband'] = key.endswith(('sat2', 'sat6'))
    return df


def _spectral_columns(df, kind):
    """ Return the spectral columns of one variable family.

    Generated by JXP and Claude.

    Args:
        df (pandas.DataFrame): A frame returned by :func:`load`.
        kind (str): Variable family (``'rrs'``, ``'aph'``, ``'acdom'``,
            ``'bbp'`` or ``'kd'``).

    Returns:
        list: ``(friendly_name, metadata)`` tuples for that family, in file
            order.
    """
    meta = df.attrs.get('columns', {})
    return [(name, m) for name, m in meta.items()
            if m.get('variable') == kind
            and m.get('role') in ('spectral', 'spectral_band')]


def spectrum(df, obs_id, kind='rrs'):
    """ Extract one observation's spectrum.

    For native-wavelength datasets the wavelength comes from the column
    metadata; for sat-band datasets it comes from the per-row ``Lambda``
    value paired with each band. Missing wavelengths are dropped.

    Generated by JXP and Claude.

    Args:
        df (pandas.DataFrame): A frame returned by :func:`load`.
        obs_id (int): Observation ``ID`` (index value) to extract.
        kind (str): Variable family to extract (default ``'rrs'``).

    Returns:
        pandas.Series: Values indexed by wavelength (nm, float), sorted by
            wavelength, with missing entries removed. ``Series.name`` is the
            observation ``ID``.
    """
    cols = _spectral_columns(df, kind)
    waves, values = [], []
    row = df.loc[obs_id]
    for name, m in cols:
        if m['role'] == 'spectral':
            wv = m['wavelength']
        else:
            # Sat-band: the true wavelength is in the paired Lambda column.
            lam_col = m.get('lambda_col')
            wv = row[lam_col] if lam_col is not None else np.nan
        waves.append(wv)
        values.append(row[name])

    out = pandas.Series(values, index=waves, name=obs_id, dtype=float)
    # Drop entries with no wavelength or no value, then sort by wavelength.
    out = out[pandas.notna(out.index)]
    out = out.dropna().sort_index()
    out.index.name = 'wavelength'
    return out


def to_long(df, kind='rrs'):
    """ Reshape one variable family into a long / tidy DataFrame.

    This is a convenience for cross-observation analysis. For per-spectrum
    extraction prefer :func:`spectrum`.

    Generated by JXP and Claude.

    Args:
        df (pandas.DataFrame): A frame returned by :func:`load`.
        kind (str): Variable family to reshape (default ``'rrs'``).

    Returns:
        pandas.DataFrame: Columns ``ID``, ``wavelength``, ``value`` and,
            for sat-band data, ``sensor`` and ``band``. Rows with a missing
            value are dropped.
    """
    cols = _spectral_columns(df, kind)
    frames = []
    for name, m in cols:
        if m['role'] == 'spectral':
            # Native: one fixed wavelength for the whole column.
            piece = df[[name]].rename(columns={name: 'value'})
            piece['wavelength'] = m['wavelength']
            piece['sensor'] = None
            piece['band'] = None
        else:
            # Sat-band: pull the per-row wavelength from the Lambda column.
            lam_col = m.get('lambda_col')
            piece = df[[name]].rename(columns={name: 'value'})
            piece['wavelength'] = (df[lam_col] if lam_col is not None
                                   else np.nan)
            piece['sensor'] = m['sensor']
            piece['band'] = m['band']
        frames.append(piece)

    if not frames:
        return pandas.DataFrame(
            columns=['ID', 'wavelength', 'value', 'sensor', 'band'])

    long = pandas.concat(frames).reset_index()
    long = long.rename(columns={long.columns[0]: 'ID'})
    long = long.dropna(subset=['value'])
    # Order columns predictably.
    return long[['ID', 'wavelength', 'value', 'sensor', 'band']]


def column_metadata(df):
    """ Return the per-column metadata mapping for a loaded dataset.

    Generated by JXP and Claude.

    Args:
        df (pandas.DataFrame): A frame returned by :func:`load`.

    Returns:
        dict: Mapping of friendly column name -> metadata dict (original
            name, unit, long name, parsed wavelength, sensor, band, ...).
    """
    return df.attrs.get('columns', {})


def n_spectral(df, kind='rrs'):
    """ Count valid spectral points per observation for one variable.

    Generated by JXP and Claude.

    Args:
        df (pandas.DataFrame): A frame returned by :func:`load`.
        kind (str): Variable family (default ``'rrs'``).

    Returns:
        pandas.Series: Number of finite values, indexed by observation
            ``ID``.
    """
    cols = [n for n, _ in _spectral_columns(df, kind)]
    if not cols:
        return pandas.Series(0, index=df.index)
    return df[cols].notna().sum(axis=1)


def extract_hyperspectral(nband, path=None,
                          iop_kinds=('aph', 'acdom', 'bbp', 'kd'),
                          include_chla=True):
    """ Extract hyperspectral Rrs spectra and their associated IOP data.

    Selects every observation whose Rrs spectrum has **more than** ``nband``
    valid wavelengths, builds an :class:`ocpy.spectra.Spectrum` for it (via
    :func:`ocpy.spectra.io.from_panagea`), gathers whatever IOP spectra share
    the same observation ``ID`` into an :class:`ocpy.spectra.SpectrumStack`,
    and attaches scalar ancillaries. The result is a dictionary keyed by
    observation ``ID``; each value is a record (dict) of Spectrum /
    SpectrumStack objects, floats and ints.

    Generated by JXP and Claude.

    Args:
        nband (int): Minimum number of Rrs wavelengths (strictly greater
            than this many valid points are kept).
        path (str, optional): Explicit ``V3`` directory (see
            :func:`panagea_path`).
        iop_kinds (tuple): IOP variable families to gather when present
            (default ``('aph', 'acdom', 'bbp', 'kd')``).
        include_chla (bool): If True, attach the merged chlorophyll value
            (HPLC, falling back to fluorometric) as ``chla``.

    Returns:
        dict: ``{obs_id: record}`` where each ``record`` has keys:
            ``id`` (int), ``rrs`` (Spectrum), ``n_rrs`` (int),
            ``iops`` (SpectrumStack), ``iop_kinds`` (list of str),
            ``tss`` (float or None; total suspended matter),
            ``lat`` / ``lon`` / ``depth`` (float or None),
            ``date`` (np.datetime64 or None) and, if requested,
            ``chla`` (float or None).
    """
    # Lazy import keeps the panagea module independent of ocpy.spectra
    # unless this extractor is actually used.
    from ocpy.spectra import io as spectra_io
    from ocpy.spectra import SpectrumStack

    # 1. Find the hyperspectral Rrs observations.
    rrs = load('rrs', path=path)
    counts = n_spectral(rrs, kind='rrs')
    keep_ids = counts.index[counts > nband]

    # 2. Pre-load the IOP table and chlorophyll once (reused per obs).
    iop = load('iop', path=path)
    iop_ids = set(iop.index)
    # TSM (tss) is a scalar member of the IOP table, captured separately.
    has_tss = 'tss' in iop.columns
    if include_chla:
        chla = load('chla', path=path)
        chl = chla['chla_hplc'].fillna(chla['chla_fluor'])
    else:
        chl = None

    # 3. Build one record per kept observation.
    out = {}
    for obs in keep_ids:
        rrs_spec = spectra_io.from_panagea(rrs, obs, kind='rrs')

        # Gather any IOP spectra for this same observation ID.
        iop_specs = []
        tss = None
        if obs in iop_ids:
            for kind in iop_kinds:
                s = spectra_io.from_panagea(iop, obs, kind=kind)
                if len(s) > 0:  # keep only families with real data
                    iop_specs.append(s)
            # Scalar TSM, if present for this observation.
            if has_tss:
                tval = iop.at[obs, 'tss']
                tss = float(tval) if pandas.notna(tval) else None

        record = {
            'id': int(obs),
            'rrs': rrs_spec,
            'n_rrs': len(rrs_spec),
            'iops': SpectrumStack(iop_specs),
            'iop_kinds': [s.metadata.get('kind') for s in iop_specs],
            'tss': tss,
            'lat': rrs_spec.lat,
            'lon': rrs_spec.lon,
            'depth': rrs_spec.depth,
            'date': rrs_spec.date,
        }
        if chl is not None:
            val = chl.get(obs)
            record['chla'] = (float(val) if val is not None
                              and pandas.notna(val) else None)
        out[obs] = record

    return out
