""" Tests for phytoplankton """
import pandas

from ocpy.ph import load_data


def test_stramski2001():
    """ Verify the Stramski et al. 2001 phytoplankton tables load.

    Inputs:
        None.
    Outputs:
        None.  Asserts that load_data.stramski2001() returns a dict
        whose 'table1' entry is a non-empty pandas DataFrame.

    Generated by JXP and Claude.
    """
    # stramski2001() is the successor to the old io.load_tables()
    # entry point, removed when ph/io.py became ph/load_data.py.
    tables = load_data.stramski2001()

    assert isinstance(tables, dict)
    assert 'table1' in tables
    assert isinstance(tables['table1'], pandas.DataFrame)
    assert len(tables['table1']) > 0
