""" Lightweight spectrum classes for ocpy.

Two small, numpy-backed containers:

- :class:`Spectrum` -- a single spectrum (one wavelength axis).
- :class:`SpectrumStack` -- a collection of :class:`Spectrum`, backed by a
  plain list so ragged members (different / different-length wavelength
  grids) are always representable. A 2D gridded view is materialized lazily
  when the members share a common grid.

Per the project requirements the heavy lifting (rebinning, interpolation) is
done by the free functions in :mod:`ocpy.spectra.utils`, which operate on
basic numpy arrays; the methods here are thin wrappers that carry the
provenance along.
"""
import json
import dataclasses
from dataclasses import dataclass, field

import numpy as np

from ocpy.spectra import utils


# --------------------------------------------------------------------
# Provenance <-> netCDF-safe attribute helpers (module-level, reused by
# both classes).
# --------------------------------------------------------------------
def _date_to_iso(date):
    """ Convert a date-like value to an ISO-8601 string.

    Generated by JXP and Claude.

    Args:
        date: ``np.datetime64``, ``datetime``, ``pandas.Timestamp`` or str.

    Returns:
        str: ISO-8601 representation.
    """
    # A string is assumed already ISO-ish; everything else goes via
    # np.datetime64 which renders ISO-8601.
    if isinstance(date, str):
        return date
    return str(np.datetime64(date))


def _iso_to_date(text):
    """ Parse an ISO-8601 string back to ``np.datetime64`` (or None).

    Generated by JXP and Claude.

    Args:
        text (str): ISO-8601 string, or an empty string / None.

    Returns:
        np.datetime64 or None.
    """
    if text is None or text == '':
        return None
    return np.datetime64(text)


# --------------------------------------------------------------------
# Spectrum
# --------------------------------------------------------------------
@dataclass
class Spectrum:
    """ A single spectrum with its provenance.

    Generated by JXP and Claude.

    Attributes:
        wavelength (np.ndarray): Wavelengths (nm), 1D, sorted ascending.
        values (np.ndarray): Values, same length as ``wavelength``.
        errors (np.ndarray or None): 1-sigma errors, same length if given.
        units (str or None): Opaque units string (e.g. ``'1/sr'``).
        source (str or None): Where the data came from.
        date (np.datetime64 or None): Observation date/time.
        lat (float or None): Latitude (deg).
        lon (float or None): Longitude (deg).
        depth (float or None): Depth (m).
        quality (dict or None): Named QF flags kept separate, e.g.
            ``{'qf_time': 0}``.
        metadata (dict): Free-form extra metadata (richer location, sensor /
            band, ...).
    """
    wavelength: np.ndarray
    values: np.ndarray
    errors: np.ndarray = None
    units: str = None
    source: str = None
    date: np.datetime64 = None
    lat: float = None
    lon: float = None
    depth: float = None
    quality: dict = None
    metadata: dict = field(default_factory=dict)

    def __post_init__(self):
        """ Coerce arrays, validate lengths, and sort by wavelength.

        Generated by JXP and Claude.
        """
        # Coerce to float numpy arrays.
        self.wavelength = np.asarray(self.wavelength, dtype=float)
        self.values = np.asarray(self.values, dtype=float)
        if self.wavelength.ndim != 1 or self.values.ndim != 1:
            raise ValueError('wavelength and values must be 1D')
        if self.wavelength.shape != self.values.shape:
            raise ValueError(
                'wavelength and values must have the same length '
                f'({self.wavelength.size} vs {self.values.size})')
        if self.errors is not None:
            self.errors = np.asarray(self.errors, dtype=float)
            if self.errors.shape != self.values.shape:
                raise ValueError(
                    'errors must match values length')

        # Keep wavelength ascending so downstream interpolation is safe.
        if self.wavelength.size and np.any(np.diff(self.wavelength) < 0):
            srt = np.argsort(self.wavelength)
            self.wavelength = self.wavelength[srt]
            self.values = self.values[srt]
            if self.errors is not None:
                self.errors = self.errors[srt]

    def __len__(self):
        """ Number of wavelength points. Generated by JXP and Claude. """
        return int(self.wavelength.size)

    def __repr__(self):
        """ Compact summary. Generated by JXP and Claude. """
        n = len(self)
        if n:
            rng = (f'{self.wavelength.min():.1f}-'
                   f'{self.wavelength.max():.1f} nm')
        else:
            rng = 'empty'
        return (f'<Spectrum n={n} {rng} '
                f'units={self.units or "?"} '
                f'source={self.source or "?"}>')

    # -- operations (delegate to utils) ------------------------------
    def rebin(self, wv_grid, method='interp'):
        """ Rebin onto a new wavelength grid.

        Generated by JXP and Claude.

        Args:
            wv_grid (np.ndarray): For ``method='interp'`` the target
                wavelengths; for ``method='bin'`` the bin edges.
            method (str): ``'interp'`` (interpolation) or ``'bin'`` (bin
                averaging).

        Returns:
            Spectrum: A new spectrum on the new grid; provenance is carried
                over.
        """
        wv_grid = np.asarray(wv_grid, dtype=float)
        if method == 'interp':
            new_v, new_e = utils.rebin(
                self.wavelength, self.values, wv_grid,
                err_vals=self.errors)
            new_wv = wv_grid
        elif method == 'bin':
            # rebin_to_grid works on a stack; feed a single row.
            err_in = (self.errors if self.errors is not None
                      else np.zeros_like(self.values))
            new_wv, vv, ee = utils.rebin_to_grid(
                self.wavelength, self.values, err_in, wv_grid)
            new_v, new_e = vv[0], ee[0]
        else:
            raise ValueError(f"Unknown method '{method}'")

        # Preserve the None-ness of errors.
        new_err = new_e if self.errors is not None else None
        # replace() copies all provenance fields onto a fresh instance.
        return dataclasses.replace(
            self, wavelength=new_wv, values=new_v, errors=new_err)

    def value_at(self, wv, kind='linear'):
        """ Interpolate the value at one or more wavelengths.

        Generated by JXP and Claude.

        Args:
            wv (float or np.ndarray): Wavelength(s) (nm).
            kind (str): Interpolation kind (default ``'linear'``).

        Returns:
            float or np.ndarray: Interpolated value(s).
        """
        return utils.value_at(self.wavelength, self.values, wv, kind=kind)

    # -- xarray / netCDF interop -------------------------------------
    def _provenance_attrs(self):
        """ Build a netCDF-safe attrs dict from the provenance.

        Generated by JXP and Claude.

        Returns:
            dict: Attributes with None values omitted; ``date`` as ISO
                string; ``quality`` / ``metadata`` as JSON strings;
                ``has_errors`` flag so None errors round-trip.
        """
        attrs = {'has_errors': int(self.errors is not None)}
        if self.units is not None:
            attrs['units'] = self.units
        if self.source is not None:
            attrs['source'] = self.source
        if self.date is not None:
            attrs['date'] = _date_to_iso(self.date)
        if self.lat is not None:
            attrs['lat'] = float(self.lat)
        if self.lon is not None:
            attrs['lon'] = float(self.lon)
        if self.depth is not None:
            attrs['depth'] = float(self.depth)
        # Dicts can't live in netCDF attrs -> JSON strings (default=str
        # guards against stray numpy scalars).
        if self.quality:
            attrs['quality_json'] = json.dumps(self.quality, default=str)
        if self.metadata:
            attrs['metadata_json'] = json.dumps(self.metadata, default=str)
        return attrs

    @staticmethod
    def _provenance_from_attrs(attrs):
        """ Inverse of :meth:`_provenance_attrs`.

        Generated by JXP and Claude.

        Args:
            attrs (dict): Dataset attributes.

        Returns:
            dict: Keyword arguments for the :class:`Spectrum` constructor
                (excluding the arrays).
        """
        out = {
            'units': attrs.get('units'),
            'source': attrs.get('source'),
            'date': _iso_to_date(attrs.get('date')),
            'lat': float(attrs['lat']) if 'lat' in attrs else None,
            'lon': float(attrs['lon']) if 'lon' in attrs else None,
            'depth': float(attrs['depth']) if 'depth' in attrs else None,
        }
        q = attrs.get('quality_json')
        out['quality'] = json.loads(q) if q else None
        m = attrs.get('metadata_json')
        out['metadata'] = json.loads(m) if m else {}
        return out

    def to_xarray(self):
        """ Convert to an ``xarray.Dataset``.

        Layout (per design): wavelength is a *data variable*, not a
        coordinate. A bare index dimension ``channel`` carries three data
        variables -- ``wavelength``, ``values``, ``errors`` -- and the
        provenance lives in ``.attrs``.

        Generated by JXP and Claude.

        Returns:
            xarray.Dataset: The spectrum as a dataset.
        """
        import xarray  # lazy import keeps the class lightweight

        n = len(self)
        # When errors are absent we still emit a NaN column; the
        # 'has_errors' attr lets from_xarray restore None.
        errs = (self.errors if self.errors is not None
                else np.full(n, np.nan))
        ds = xarray.Dataset(
            data_vars=dict(
                wavelength=('channel', self.wavelength),
                values=('channel', self.values),
                errors=('channel', errs),
            ),
        )
        ds.attrs.update(self._provenance_attrs())
        return ds

    @classmethod
    def from_xarray(cls, ds):
        """ Build a :class:`Spectrum` from an ``xarray.Dataset``.

        Generated by JXP and Claude.

        Args:
            ds (xarray.Dataset): As produced by :meth:`to_xarray`.

        Returns:
            Spectrum
        """
        wv = np.asarray(ds['wavelength'].values, dtype=float)
        val = np.asarray(ds['values'].values, dtype=float)
        has_err = bool(int(ds.attrs.get('has_errors', 1)))
        err = (np.asarray(ds['errors'].values, dtype=float)
               if has_err else None)
        kwargs = cls._provenance_from_attrs(ds.attrs)
        return cls(wavelength=wv, values=val, errors=err, **kwargs)

    def to_netcdf(self, path, **kwargs):
        """ Write to a netCDF file via :meth:`to_xarray`.

        Generated by JXP and Claude.

        Args:
            path (str): Output path.
            **kwargs: Passed to ``xarray.Dataset.to_netcdf``.
        """
        self.to_xarray().to_netcdf(path, **kwargs)

    @classmethod
    def read_netcdf(cls, path):
        """ Read a :class:`Spectrum` from a netCDF file.

        Generated by JXP and Claude.

        Args:
            path (str): Input path.

        Returns:
            Spectrum
        """
        import xarray
        with xarray.open_dataset(path) as ds:
            ds = ds.load()
        return cls.from_xarray(ds)

    # -- plotting ----------------------------------------------------
    def plot(self, ax=None, **kwargs):
        """ Plot the spectrum with matplotlib.

        Generated by JXP and Claude.

        Args:
            ax (matplotlib.axes.Axes, optional): Axis to draw on; created if
                None.
            **kwargs: Passed to ``ax.plot``.

        Returns:
            matplotlib.axes.Axes: The axis drawn on.
        """
        import matplotlib.pyplot as plt

        if ax is None:
            _, ax = plt.subplots()
        ax.plot(self.wavelength, self.values, **kwargs)
        # Shade the 1-sigma band when errors are present.
        if self.errors is not None:
            ax.fill_between(self.wavelength,
                            self.values - self.errors,
                            self.values + self.errors,
                            alpha=0.3)
        ax.set_xlabel('Wavelength (nm)')
        ax.set_ylabel(f'Value [{self.units}]' if self.units else 'Value')
        return ax


# --------------------------------------------------------------------
# SpectrumStack
# --------------------------------------------------------------------
@dataclass
class SpectrumStack:
    """ A collection of :class:`Spectrum`, possibly ragged.

    Generated by JXP and Claude.

    Attributes:
        spectra (list): List of :class:`Spectrum` instances.
    """
    spectra: list = field(default_factory=list)

    def __post_init__(self):
        """ Validate the members. Generated by JXP and Claude. """
        for s in self.spectra:
            if not isinstance(s, Spectrum):
                raise TypeError(
                    'SpectrumStack members must be Spectrum instances')

    # -- container protocol ------------------------------------------
    def __len__(self):
        """ Number of spectra. Generated by JXP and Claude. """
        return len(self.spectra)

    def __iter__(self):
        """ Iterate over member spectra. Generated by JXP and Claude. """
        return iter(self.spectra)

    def __getitem__(self, idx):
        """ Index / slice members. Generated by JXP and Claude. """
        return self.spectra[idx]

    def __repr__(self):
        """ Compact summary. Generated by JXP and Claude. """
        grid = 'gridded' if self.is_gridded else 'ragged'
        return f'<SpectrumStack n={len(self)} {grid}>'

    # -- gridding ----------------------------------------------------
    @property
    def is_gridded(self):
        """ True if all members share one wavelength grid.

        Generated by JXP and Claude.

        Returns:
            bool
        """
        return utils.common_grid([s.wavelength for s in self.spectra])

    def as_array(self):
        """ Return ``(wavelength, values_2d, errors_2d)`` for a gridded stack.

        Generated by JXP and Claude.

        Returns:
            tuple: ``wavelength`` (nwave,), ``values`` (nspec, nwave),
                ``errors`` (nspec, nwave). Members without errors contribute
                NaN rows.

        Raises:
            ValueError: If the stack is ragged (call :meth:`rebin` first).
        """
        if not self.is_gridded:
            raise ValueError(
                'Stack is ragged; rebin(wv_grid) onto a common grid before '
                'calling as_array().')
        if len(self.spectra) == 0:
            empty = np.zeros((0, 0))
            return np.zeros(0), empty, empty

        wv = self.spectra[0].wavelength
        values = np.vstack([s.values for s in self.spectra])
        errors = np.vstack([
            s.errors if s.errors is not None
            else np.full_like(s.values, np.nan)
            for s in self.spectra])
        return wv, values, errors

    def rebin(self, wv_grid, method='interp'):
        """ Rebin every member onto ``wv_grid`` -> a gridded stack.

        Generated by JXP and Claude.

        Args:
            wv_grid (np.ndarray): Target grid / bin edges (see
                :meth:`Spectrum.rebin`).
            method (str): ``'interp'`` or ``'bin'``.

        Returns:
            SpectrumStack: A new, gridded stack.
        """
        return SpectrumStack(
            [s.rebin(wv_grid, method=method) for s in self.spectra])

    # -- per-spectrum provenance accessors ---------------------------
    @property
    def dates(self):
        """ Per-spectrum dates. Generated by JXP and Claude. """
        return np.array([s.date for s in self.spectra])

    @property
    def lats(self):
        """ Per-spectrum latitudes. Generated by JXP and Claude. """
        return np.array([s.lat for s in self.spectra], dtype=float)

    @property
    def lons(self):
        """ Per-spectrum longitudes. Generated by JXP and Claude. """
        return np.array([s.lon for s in self.spectra], dtype=float)

    @property
    def depths(self):
        """ Per-spectrum depths. Generated by JXP and Claude. """
        return np.array([s.depth for s in self.spectra], dtype=float)

    @property
    def sources(self):
        """ Per-spectrum sources. Generated by JXP and Claude. """
        return np.array([s.source for s in self.spectra], dtype=object)

    # -- xarray / netCDF interop -------------------------------------
    def to_xarray(self):
        """ Convert to an ``xarray.Dataset`` (gridded or ragged).

        Because wavelength is a data variable (not a coordinate), ragged
        members are handled by NaN-padding every row to the longest member;
        the per-row ``wavelength`` variable records the true grid so the pad
        is unambiguous. Provenance is stored as a JSON list-of-dicts in
        ``.attrs['provenance_json']`` (netCDF-safe, fully round-trippable).

        Generated by JXP and Claude.

        Returns:
            xarray.Dataset: dims ``(spectrum, channel)``.
        """
        import xarray

        nspec = len(self.spectra)
        maxlen = max((len(s) for s in self.spectra), default=0)

        wv = np.full((nspec, maxlen), np.nan)
        val = np.full((nspec, maxlen), np.nan)
        err = np.full((nspec, maxlen), np.nan)
        prov = []
        for i, s in enumerate(self.spectra):
            n = len(s)
            wv[i, :n] = s.wavelength
            val[i, :n] = s.values
            if s.errors is not None:
                err[i, :n] = s.errors
            # Reuse the single-spectrum attrs builder for each member.
            prov.append(s._provenance_attrs())

        ds = xarray.Dataset(
            data_vars=dict(
                wavelength=(('spectrum', 'channel'), wv),
                values=(('spectrum', 'channel'), val),
                errors=(('spectrum', 'channel'), err),
            ),
        )
        ds.attrs['provenance_json'] = json.dumps(prov)
        return ds

    @classmethod
    def from_xarray(cls, ds):
        """ Build a :class:`SpectrumStack` from an ``xarray.Dataset``.

        Generated by JXP and Claude.

        Args:
            ds (xarray.Dataset): As produced by :meth:`to_xarray`.

        Returns:
            SpectrumStack
        """
        prov = json.loads(ds.attrs.get('provenance_json', '[]'))
        wv_all = np.asarray(ds['wavelength'].values, dtype=float)
        val_all = np.asarray(ds['values'].values, dtype=float)
        err_all = np.asarray(ds['errors'].values, dtype=float)

        spectra = []
        nspec = wv_all.shape[0]
        for i in range(nspec):
            wv = wv_all[i]
            # Drop the NaN pad using the wavelength row as the mask.
            good = np.isfinite(wv)
            attrs = prov[i] if i < len(prov) else {}
            has_err = bool(int(attrs.get('has_errors', 1)))
            err = err_all[i][good] if has_err else None
            kwargs = Spectrum._provenance_from_attrs(attrs)
            spectra.append(Spectrum(
                wavelength=wv[good], values=val_all[i][good],
                errors=err, **kwargs))
        return cls(spectra)

    def to_netcdf(self, path, **kwargs):
        """ Write the stack to netCDF. Generated by JXP and Claude.

        Args:
            path (str): Output path.
            **kwargs: Passed to ``xarray.Dataset.to_netcdf``.
        """
        self.to_xarray().to_netcdf(path, **kwargs)

    @classmethod
    def read_netcdf(cls, path):
        """ Read a stack from netCDF. Generated by JXP and Claude.

        Args:
            path (str): Input path.

        Returns:
            SpectrumStack
        """
        import xarray
        with xarray.open_dataset(path) as ds:
            ds = ds.load()
        return cls.from_xarray(ds)
