""" Source adapters: build Spectrum / SpectrumStack from ocpy datasets.

These functions only *map* the output of the existing loaders
(:mod:`ocpy.insitu.pangaea`, :mod:`ocpy.hydrolight.loisel23`,
:mod:`ocpy.tara.spectra`) into the lightweight classes -- they reuse those
modules rather than re-reading files. Heavy source modules are imported
lazily inside each function so that ``import ocpy.spectra.io`` stays cheap.
"""
import numpy as np
import pandas

from ocpy.spectra.core import Spectrum, SpectrumStack


def _get(row, key):
    """ Safely fetch a scalar from a row, returning None if absent / NaN.

    Generated by JXP and Claude.

    Args:
        row (pandas.Series): A table row.
        key (str): Column name.

    Returns:
        The value, or None if the column is missing or the value is NaN.
    """
    if key in row.index:
        val = row[key]
        if pandas.notna(val):
            return val
    return None


# --------------------------------------------------------------------
# PANGAEA
# --------------------------------------------------------------------
def _pangaea_units(meta, kind):
    """ Return the unit string for a PANGAEA variable family.

    Generated by JXP and Claude.

    Args:
        meta (dict): Per-column metadata (``pangaea.column_metadata``).
        kind (str): Variable family (e.g. ``'rrs'``).

    Returns:
        str or None: The unit of the first matching spectral column.
    """
    for name, m in meta.items():
        if (m.get('variable') == kind
                and m.get('role') in ('spectral', 'spectral_band')):
            return m.get('unit')
    return None


def from_pangaea(df, obs_id, kind='rrs'):
    """ Build a :class:`Spectrum` from one PANGAEA observation.

    Generated by JXP and Claude.

    Args:
        df (pandas.DataFrame): Frame from :func:`ocpy.insitu.pangaea.load`.
        obs_id: Observation ``ID`` (index value).
        kind (str): Variable family to extract (default ``'rrs'``).

    Returns:
        Spectrum: Wavelength/value from ``pangaea.spectrum``; units from the
            column metadata; date/lat/lon/depth and any QF flags from the
            row; dataset/subdataset/contributor stashed in ``metadata``.
    """
    from ocpy.insitu import pangaea

    # Reuse the existing extractor: a wavelength-indexed Series.
    sp = pangaea.spectrum(df, obs_id, kind=kind)
    row = df.loc[obs_id]
    meta = pangaea.column_metadata(df)

    # Date -> np.datetime64 when present.
    date = _get(row, 'date_time')
    date = np.datetime64(date) if date is not None else None

    # QF flags kept separate (Q6): all columns flagged role 'qf'.
    quality = {name: row[name] for name, m in meta.items()
               if m.get('role') == 'qf' and name in row.index}

    # Provenance comment columns -> metadata.
    metadata = {name: row[name] for name, m in meta.items()
                if m.get('role') == 'provenance' and name in row.index}
    metadata['obs_id'] = obs_id
    metadata['kind'] = kind

    return Spectrum(
        wavelength=sp.index.values.astype(float),
        values=sp.values.astype(float),
        errors=None,
        units=_pangaea_units(meta, kind),
        source='PANGAEA',
        date=date,
        lat=_get(row, 'lat'),
        lon=_get(row, 'lon'),
        depth=_get(row, 'depth_m'),
        quality=quality or None,
        metadata=metadata,
    )


def stack_from_pangaea(df, kind='rrs', ids=None):
    """ Build a :class:`SpectrumStack` from PANGAEA observations.

    Generated by JXP and Claude.

    Args:
        df (pandas.DataFrame): Frame from :func:`ocpy.insitu.pangaea.load`.
        kind (str): Variable family (default ``'rrs'``).
        ids (iterable, optional): Observation IDs; defaults to all rows.

    Returns:
        SpectrumStack: One member per observation; observations with no valid
            points are skipped (so the stack is generally ragged).
    """
    if ids is None:
        ids = df.index
    spectra = []
    for obs in ids:
        s = from_pangaea(df, obs, kind=kind)
        if len(s) > 0:  # skip observations with no valid samples
            spectra.append(s)
    return SpectrumStack(spectra)


# --------------------------------------------------------------------
# Loisel+2023 Hydrolight
# --------------------------------------------------------------------
def from_loisel23(ds, index, var='Rrs', units=None):
    """ Build a :class:`Spectrum` from one Loisel+2023 simulation.

    The Loisel+2023 files carry no per-variable unit metadata, so ``units``
    defaults to None; pass it explicitly if you know the convention (Rrs is
    1/sr; absorption/scattering terms are 1/m).

    Generated by JXP and Claude.

    Args:
        ds (xarray.Dataset): Dataset from
            :func:`ocpy.hydrolight.loisel23.load_ds`.
        index (int): Row index along the ``IOP_Scenario`` dimension.
        var (str): Variable name (default ``'Rrs'``; others include
            ``'a'``, ``'aph'``, ``'bb'``, ...).
        units (str, optional): Units string to record.

    Returns:
        Spectrum: Errors are None (simulations); ``metadata`` records the
            scenario index and variable.
    """
    # Lambda is a shared coordinate; the variable is (IOP_Scenario, Lambda).
    wv = np.asarray(ds['Lambda'].values, dtype=float)
    values = np.asarray(ds[var].values[index], dtype=float)
    return Spectrum(
        wavelength=wv,
        values=values,
        errors=None,
        units=units,
        source='Loisel2023',
        metadata={'scenario_index': int(index), 'variable': var},
    )


def stack_from_loisel23(ds, var='Rrs', indices=None, units=None):
    """ Build a gridded :class:`SpectrumStack` from Loisel+2023 simulations.

    All simulations share the ``Lambda`` grid, so the result is gridded.

    Generated by JXP and Claude.

    Args:
        ds (xarray.Dataset): Dataset from
            :func:`ocpy.hydrolight.loisel23.load_ds`.
        var (str): Variable name (default ``'Rrs'``).
        indices (iterable, optional): Scenario indices; defaults to all.
        units (str, optional): Units string to record on each member.

    Returns:
        SpectrumStack
    """
    nspec = ds[var].shape[0]
    if indices is None:
        indices = range(nspec)
    spectra = [from_loisel23(ds, i, var=var, units=units)
               for i in indices]
    return SpectrumStack(spectra)


# --------------------------------------------------------------------
# Tara Oceans
# --------------------------------------------------------------------
def from_tara(row, flavor='ap'):
    """ Build a :class:`Spectrum` from one Tara Oceans row.

    Reuses :func:`ocpy.tara.spectra.spectrum_from_row`. The ``ap`` / ``cp``
    families are in 1/m. Latitude/longitude/date are pulled from the row when
    present (column names vary between Tara tables, so they are looked up
    defensively).

    Generated by JXP and Claude.

    Args:
        row (pandas.Series): One row of a Tara Oceans table.
        flavor (str): Spectrum flavor, ``'ap'`` or ``'cp'`` (default
            ``'ap'``).

    Returns:
        Spectrum
    """
    from ocpy.tara import spectra as tara_spectra

    wv, values, errs = tara_spectra.spectrum_from_row(row, flavor=flavor)

    # Defensive provenance lookup across a few candidate column names.
    lat = _get(row, 'lat')
    if lat is None:
        lat = _get(row, 'Latitude')
    lon = _get(row, 'lon')
    if lon is None:
        lon = _get(row, 'Longitude')

    # Prefer a real timestamp column; the integer 'date' (YYYYMMDD) is a
    # fallback that must be parsed explicitly (np.datetime64 would otherwise
    # misread the integer).
    dt = _get(row, 'datetime')
    if dt is not None:
        date = np.datetime64(dt)
    else:
        raw = _get(row, 'date')
        date = (np.datetime64(pandas.to_datetime(str(int(raw)),
                                                 format='%Y%m%d'))
                if raw is not None else None)

    # Ancillary fields (cruise, salinity, water temperature) -> metadata.
    metadata = {'flavor': flavor}
    for key in ('cruise', 'sal', 'Wt'):
        val = _get(row, key)
        if val is not None:
            metadata[key] = val

    return Spectrum(
        wavelength=np.asarray(wv, dtype=float),
        values=np.asarray(values, dtype=float),
        errors=np.asarray(errs, dtype=float),
        units='1/m',
        source='Tara',
        date=date,
        lat=lat,
        lon=lon,
        metadata=metadata,
    )


def stack_from_tara(tbl, flavor='ap'):
    """ Build a :class:`SpectrumStack` from a Tara Oceans table.

    Generated by JXP and Claude.

    Args:
        tbl (pandas.DataFrame): A Tara Oceans table.
        flavor (str): Spectrum flavor (default ``'ap'``).

    Returns:
        SpectrumStack: One member per row; empty rows are skipped.
    """
    spectra = []
    for i in range(len(tbl)):
        s = from_tara(tbl.iloc[i], flavor=flavor)
        if len(s) > 0:
            spectra.append(s)
    return SpectrumStack(spectra)
