""" Array-level utilities for spectra.

These are deliberately written as free functions that operate on basic
Python objects (numpy arrays, floats) rather than classes, so they can be
reused both by the ``Spectrum`` / ``SpectrumStack`` classes and by callers
working with raw arrays.
"""

import numpy as np
from scipy.interpolate import interp1d


def rebin(wv_nm:np.ndarray, values:np.ndarray,
          wv_grid:np.ndarray,
          err_vals:np.ndarray=None):
    """ Rebin a single spectrum to a new wavelength grid by interpolation.

    Note: errors are interpolated point-by-point, not formally propagated
    through the interpolation. For the use cases here that is the intended
    behaviour (the errors are treated as a co-located 1-sigma curve).

    Generated by JXP and Claude.

    Args:
        wv_nm (np.ndarray): Wavelengths (nm).
        values (np.ndarray): Values.
        wv_grid (np.ndarray): New wavelength grid (nm).
        err_vals (np.ndarray, optional): 1-sigma error values.

    Returns:
        tuple: ``(new_values, new_err)`` as np.ndarray. When ``err_vals`` is
            None, ``new_err`` is an array of zeros matching ``new_values``.
    """
    # Interpolate; values outside the input range become NaN.
    f_values = interp1d(wv_nm, values,
        bounds_error=False, fill_value=np.nan)
    if err_vals is not None:
        f_err = interp1d(wv_nm, err_vals,
            bounds_error=False, fill_value=np.nan)

    # Evaluate on the requested grid.
    new_values = f_values(wv_grid)
    if err_vals is not None:
        new_err = f_err(wv_grid)
    else:
        new_err = np.zeros_like(new_values)

    # Return
    return new_values, new_err


def rebin_to_grid(wv_nm:np.ndarray, values:np.ndarray,
                  err_vals:np.ndarray, wv_grid:np.ndarray):
    """ Rebin a stack of spectra to a new grid by bin averaging.

    Simple nearest-neighbour binning (no interpolation): each output bin is
    the mean of the input points whose wavelength falls in ``[w0, w1)``,
    ignoring NaNs.

    Shape convention (fixed in this refactor): ``values`` and ``err_vals``
    are spectrum-major, ``(nspec, nwave)``, and the returned arrays are
    likewise ``(nspec, nbin)`` so the convention is consistent end to end.
    A 1D input is promoted to a single-row stack.

    Generated by JXP and Claude.

    Args:
        wv_nm (np.ndarray): Wavelengths (nm), shape ``(nwave,)``.
        values (np.ndarray): Values, shape ``(nspec, nwave)``.
        err_vals (np.ndarray): 1-sigma errors, shape ``(nspec, nwave)``.
        wv_grid (np.ndarray): Bin edges (nm); produces ``len(wv_grid)-1``
            bins.

    Returns:
        tuple: ``(rebin_wave, rebin_values, rebin_err)`` with shapes
            ``(nbin,)``, ``(nspec, nbin)`` and ``(nspec, nbin)``. Bins with
            no input points are filled with NaN.
    """
    # Promote a single spectrum to a 1-row stack so the logic is uniform.
    values = np.atleast_2d(values)
    err_vals = np.atleast_2d(err_vals)

    nspec = values.shape[0]
    nbin = wv_grid.size - 1

    # Mask of finite samples; used to ignore NaNs in the bin averages.
    mask = np.isfinite(values).astype(int)

    rebin_values = np.full((nspec, nbin), np.nan)
    rebin_err = np.full((nspec, nbin), np.nan)
    rebin_wave = np.zeros(nbin)

    # Loop over output bins.
    for iwv in range(nbin):
        w0 = wv_grid[iwv]
        w1 = wv_grid[iwv + 1]
        rebin_wave[iwv] = (w0 + w1) / 2.

        # Input wavelengths falling in this bin.
        gd = np.where((wv_nm >= w0) & (wv_nm < w1))[0]
        if len(gd) == 0:
            # No samples: leave NaN (already filled) and move on.
            continue

        # Per-spectrum count of finite samples in the bin.
        mask_sum = np.sum(mask[:, gd], axis=1)

        # NaN-weighted mean; guard against empty (all-NaN) bins.
        with np.errstate(invalid='ignore', divide='ignore'):
            isum = (np.nansum(values[:, gd] * mask[:, gd], axis=1)
                    / mask_sum)
            esum = (np.nansum(err_vals[:, gd] * mask[:, gd], axis=1)
                    / mask_sum)

        rebin_values[:, iwv] = isum
        rebin_err[:, iwv] = esum

    # Return
    return rebin_wave, rebin_values, rebin_err


def value_at(wv_nm:np.ndarray, values:np.ndarray, wv,
             kind:str='linear'):
    """ Interpolate spectrum value(s) at one or more wavelengths.

    Generated by JXP and Claude.

    Args:
        wv_nm (np.ndarray): Wavelengths (nm) of the spectrum.
        values (np.ndarray): Values of the spectrum.
        wv (float or np.ndarray): Wavelength(s) (nm) to evaluate.
        kind (str, optional): Interpolation kind passed to
            ``scipy.interpolate.interp1d`` (default ``'linear'``).

    Returns:
        float or np.ndarray: Interpolated value(s). Wavelengths outside the
            input range return NaN. A scalar ``wv`` yields a float.
    """
    # Interpolator; out-of-range requests become NaN rather than raising.
    f = interp1d(wv_nm, values, kind=kind,
                 bounds_error=False, fill_value=np.nan)
    out = f(wv)

    # Preserve scalar-in / scalar-out behaviour for convenience.
    if np.ndim(wv) == 0:
        return float(out)
    return out


def common_grid(list_of_wv, rtol:float=1e-05, atol:float=1e-08):
    """ Test whether a set of wavelength arrays share one common grid.

    This drives ``SpectrumStack.is_gridded``: a stack is "gridded" when all
    members have wavelength arrays of the same length and (near-)equal
    values.

    Generated by JXP and Claude.

    Args:
        list_of_wv (list): List of wavelength np.ndarrays.
        rtol (float, optional): Relative tolerance for the comparison.
        atol (float, optional): Absolute tolerance for the comparison.

    Returns:
        bool: True if every array matches the first within tolerance (and an
            empty or single-element list is trivially common); False
            otherwise.
    """
    # 0 or 1 arrays are trivially on a common grid.
    if len(list_of_wv) <= 1:
        return True

    first = np.asarray(list_of_wv[0])
    for wv in list_of_wv[1:]:
        wv = np.asarray(wv)
        # Different length can never match.
        if wv.shape != first.shape:
            return False
        if not np.allclose(wv, first, rtol=rtol, atol=atol,
                           equal_nan=True):
            return False
    return True


def align_to_grid(list_of_wv, list_of_values, wv_grid,
                  list_of_err=None):
    """ Rebin a ragged collection of spectra onto one common grid.

    Each spectrum (with its own wavelengths) is interpolated onto
    ``wv_grid`` via :func:`rebin`, then stacked. This is the bridge from a
    ragged stack to a gridded one.

    Generated by JXP and Claude.

    Args:
        list_of_wv (list): Per-spectrum wavelength np.ndarrays.
        list_of_values (list): Per-spectrum value np.ndarrays.
        wv_grid (np.ndarray): Target wavelength grid (nm).
        list_of_err (list, optional): Per-spectrum 1-sigma error arrays. If
            None, the returned errors are zeros.

    Returns:
        tuple: ``(values_2d, err_2d)`` each of shape ``(nspec, ngrid)``.
    """
    nspec = len(list_of_values)
    ngrid = np.asarray(wv_grid).size

    out_values = np.full((nspec, ngrid), np.nan)
    out_err = np.full((nspec, ngrid), np.nan)

    # Interpolate each spectrum independently onto the shared grid.
    for i in range(nspec):
        err_i = None if list_of_err is None else list_of_err[i]
        new_v, new_e = rebin(list_of_wv[i], list_of_values[i],
                             wv_grid, err_vals=err_i)
        out_values[i] = new_v
        out_err[i] = new_e

    return out_values, out_err
